# Generated by Django 5.0.6 on 2026-04-15 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('executive_summary', models.TextField(blank=True)),
                ('methodology', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('client_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_draft', models.BooleanField(default=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdf/')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='reports/docx/')),
                ('xlsx_file', models.FileField(blank=True, null=True, upload_to='reports/xlsx/')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='engagements.engagement')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'Word Document'), ('XLSX', 'Excel'), ('HTML', 'HTML')], max_length=10)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='report_exports/')),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reports.report')),
            ],
            options={
                'ordering': ['-exported_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_global', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='template_logos/')),
                ('primary_color', models.CharField(default='#24483E', max_length=7)),
                ('secondary_color', models.CharField(default='#FFF1AA', max_length=7)),
                ('executive_summary_template', models.TextField(blank=True, help_text='Executive summary boilerplate')),
                ('methodology_template', models.TextField(blank=True, help_text='Methodology section boilerplate')),
                ('introduction_template', models.TextField(blank=True, help_text='Introduction boilerplate')),
                ('conclusion_template', models.TextField(blank=True, help_text='Conclusion boilerplate')),
                ('custom_sections', models.JSONField(blank=True, default=list, help_text='Additional custom sections')),
                ('include_cvss_table', models.BooleanField(default=True)),
                ('include_remediation_timeline', models.BooleanField(default=True)),
                ('include_appendix', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reporttemplate'),
        ),
    ]
