#!/usr/bin/env python3
"""
Generator script: reads aescsf_v2_extracted.json and writes aescsf_v2_seed_generated.py
containing the AESCSF_V2_SECTIONS list in the format expected by seed_assessment_templates.py.
"""

import json
import sys

INPUT_JSON  = r'C:\Users\Alex\Documents\ozireport\aescsf_v2_extracted.json'
OUTPUT_PY   = r'C:\Users\Alex\Documents\ozireport\aescsf_v2_seed_generated.py'
GUIDANCE_LIMIT = 600
CHOICE_OPTIONS = ['Not Implemented', 'Partially Implemented', 'Largely Implemented', 'Fully Implemented']
ANTI_OPTIONS   = ['Present', 'Not Present']


def escape_str(s: str) -> str:
    """Escape backslashes and single-quotes for use inside single-quoted Python strings."""
    s = s.replace('\\', '\\\\')
    s = s.replace("'", "\\'")
    return s


def truncate_guidance(g: str, limit: int = GUIDANCE_LIMIT) -> str:
    # Collapse all whitespace/newlines to single spaces so the string
    # stays on one line inside a single-quoted Python literal.
    g = ' '.join(g.split())
    if len(g) > limit:
        return g[:limit].rstrip() + '...'
    return g


def render_options(opts: list) -> str:
    if not opts:
        return '[]'
    inner = ', '.join(f"'{o}'" for o in opts)
    return f'[{inner}]'


def main():
    with open(INPUT_JSON, encoding='utf-8') as f:
        data = json.load(f)

    domains = data['domains']

    lines = []
    lines.append('# Auto-generated AESCSF v2 seed data — DO NOT EDIT BY HAND')
    lines.append('# Generated by generate_aescsf_v2_seed.py')
    lines.append('')
    lines.append('AESCSF_V2_SECTIONS = [')

    for domain in domains:
        domain_name = domain['name']
        sub_objectives = domain.get('sub_objectives', [])

        # Section description: join sub-objective names with " | "
        sub_names = [so['name'] for so in sub_objectives]
        section_desc = ' | '.join(sub_names)

        lines.append('    {')
        lines.append(f"        'name': '{escape_str(domain_name)}',")
        lines.append(f"        'description': '{escape_str(section_desc)}',")
        lines.append(f"        'questions': [")

        order = 1
        for so in sub_objectives:
            is_anti = so.get('is_anti_pattern', False)
            for practice in so.get('practices', []):
                pid      = practice['id']
                raw_text = practice.get('text', '')
                raw_guid = practice.get('guidance', '')
                mil      = practice.get('mil', 1)
                sp       = practice.get('sp', 1)

                # Build text with practice ID prefix
                text = f'[{pid}] {raw_text}'

                # Truncate and escape guidance
                guidance = truncate_guidance(raw_guid, GUIDANCE_LIMIT)

                # question_type & options
                if is_anti:
                    qtype   = 'CHOICE'
                    options = ANTI_OPTIONS
                    mil_val = 1
                elif mil == 1:
                    qtype   = 'YESNO'
                    options = []
                    mil_val = mil
                else:  # mil 2 or 3
                    qtype   = 'CHOICE'
                    options = CHOICE_OPTIONS
                    mil_val = mil

                weight = float(sp)

                escaped_text = escape_str(text)
                escaped_guid = escape_str(guidance)
                opts_str     = render_options(options)

                lines.append(
                    f"            ({order}, '{escaped_text}', "
                    f"'{escaped_guid}', "
                    f"'{qtype}', {mil_val}, {opts_str}, {weight}),"
                )
                order += 1

        lines.append('        ]')
        lines.append('    },')

    lines.append(']')
    lines.append('')  # trailing newline

    output = '\n'.join(lines)

    with open(OUTPUT_PY, 'w', encoding='utf-8') as f:
        f.write(output)

    print(f'Written: {OUTPUT_PY}')

    # Quick self-check
    domain_count   = len(domains)
    question_count = sum(
        len(p)
        for d in domains
        for so in d.get('sub_objectives', [])
        for p in [so.get('practices', [])]
    )
    print(f'Expected sections : {domain_count}')
    print(f'Expected questions: {question_count}')


if __name__ == '__main__':
    main()
