# Generated by Django 5.0.6 on 2026-04-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_org_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttemplate',
            name='framework',
            field=models.CharField(choices=[('ESSENTIAL_EIGHT', 'Essential Eight'), ('GAP_ANALYSIS', 'Gap Analysis'), ('CIS', 'CIS Health Check'), ('AESCSF', 'AESCSF 2023'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=30),
        ),
    ]
