# Generated by Django 5.0.6 on 2026-05-29 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_evidence_requirements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='grc_consultant',
            field=models.ForeignKey(blank=True, help_text='GRC Consultant assigned to conduct this assessment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grc_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
