from django.urls import path

from .views import (
    IntegrationLogListView,
    IntegrationOverviewView,
    JiraComponentsView,
    JiraIssueLinkListView,
    JiraFieldsView,
    JiraIssueTypesView,
    JiraParentsView,
    JiraPrioritiesView,
    JiraProjectsView,
    JiraSettingView,
    JiraSyncStatusView,
    JiraSyncFindingView,
    JiraTestIssueView,
    JiraTestView,
    JiraUsersView,
    JiraWebhookReceiverView,
    ServiceNowSettingView,
    WebhookSettingView,
    WebhookTestView,
)

urlpatterns = [
    path('', IntegrationOverviewView.as_view(), name='integrations_overview'),
    path('logs/', IntegrationLogListView.as_view(), name='integration_logs'),
    path('webhook/', WebhookSettingView.as_view(), name='webhook_setting'),
    path('webhook/test/', WebhookTestView.as_view(), name='webhook_test'),
    path('servicenow/', ServiceNowSettingView.as_view(), name='servicenow_setting'),
    path('jira/', JiraSettingView.as_view(), name='jira_setting'),
    path('jira/test/', JiraTestView.as_view(), name='jira_test'),
    path('jira/projects/', JiraProjectsView.as_view(), name='jira_projects'),
    path('jira/issue-types/', JiraIssueTypesView.as_view(), name='jira_issue_types'),
    path('jira/fields/', JiraFieldsView.as_view(), name='jira_fields'),
    path('jira/components/', JiraComponentsView.as_view(), name='jira_components'),
    path('jira/users/', JiraUsersView.as_view(), name='jira_users'),
    path('jira/parents/', JiraParentsView.as_view(), name='jira_parents'),
    path('jira/priorities/', JiraPrioritiesView.as_view(), name='jira_priorities'),
    path('jira/test-issue/', JiraTestIssueView.as_view(), name='jira_test_issue'),
    path('jira/sync-status/', JiraSyncStatusView.as_view(), name='jira_sync_status'),
    path('jira/sync-finding/', JiraSyncFindingView.as_view(), name='jira_sync_finding'),
    path('jira/webhook/', JiraWebhookReceiverView.as_view(), name='jira_webhook'),
    path('jira/issues/', JiraIssueLinkListView.as_view(), name='jira_issue_links'),
]
