# Generated by Django 5.0.6 on 2026-04-15 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingTemplateTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#24483E', help_text='Hex color code', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FindingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global', models.BooleanField(default=False, help_text='Global template available to all organizations')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('WEB', 'Web Application'), ('MOBILE', 'Mobile Application'), ('NETWORK', 'Network Infrastructure'), ('API', 'API'), ('CLOUD', 'Cloud Infrastructure'), ('SOCIAL', 'Social Engineering'), ('PHYSICAL', 'Physical Security'), ('WIRELESS', 'Wireless'), ('CONFIG', 'Misconfiguration'), ('AUTH', 'Authentication'), ('ENCRYPTION', 'Cryptography'), ('SESSION', 'Session Management'), ('INPUT', 'Input Validation'), ('ACCESS', 'Access Control'), ('LOGGING', 'Logging & Monitoring'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('impact', models.TextField()),
                ('likelihood', models.TextField()),
                ('recommendations', models.TextField()),
                ('supporting_evidence', models.TextField(blank=True)),
                ('default_severity', models.CharField(choices=[('INFORMATIONAL', 'Informational'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('cvss_vector', models.CharField(blank=True, max_length=255)),
                ('av', models.CharField(blank=True, max_length=20)),
                ('ac', models.CharField(blank=True, max_length=20)),
                ('pr', models.CharField(blank=True, max_length=20)),
                ('ui', models.CharField(blank=True, max_length=20)),
                ('s', models.CharField(blank=True, max_length=20)),
                ('c', models.CharField(blank=True, max_length=20)),
                ('i', models.CharField(blank=True, max_length=20)),
                ('a', models.CharField(blank=True, max_length=20)),
                ('references', models.TextField(blank=True)),
                ('cwe_id', models.CharField(blank=True, max_length=50)),
                ('tags', models.JSONField(default=list, help_text='List of tags for searching')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finding_templates', to='organizations.organization')),
            ],
            options={
                'ordering': ['-usage_count', 'title'],
                'indexes': [models.Index(fields=['category'], name='repository__categor_3bfe68_idx'), models.Index(fields=['is_global'], name='repository__is_glob_1f22a9_idx')],
            },
        ),
    ]
