# Generated by Django 5.0.6 on 2026-04-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_handover_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('ENGAGEMENT_START', 'Engagement Start'), ('ENGAGEMENT_END', 'Engagement End'), ('TESTING_WINDOW', 'Active Testing'), ('REPORT_DUE', 'Report Due'), ('KICKOFF', 'Kickoff Meeting'), ('DEBRIEF', 'Debrief / Closeout'), ('HANDOVER', 'Tester Handover'), ('RETEST', 'Re-test / Verification'), ('SCOPING', 'Scoping Call'), ('REMEDIATION_REVIEW', 'Remediation Review'), ('CLIENT_MEETING', 'Client Meeting'), ('INTERNAL_REVIEW', 'Internal Review'), ('LEAVE', 'Leave / Holiday'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
