# Generated by Django 5.0.6 on 2026-04-15 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('severity', models.CharField(choices=[('INFORMATIONAL', 'Informational'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Finding'), ('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('PUBLISHED', 'Published'), ('REMEDIATED', 'Remediated'), ('FALSE_POSITIVE', 'False Positive'), ('ACCEPTED_RISK', 'Risk Accepted')], default='DRAFT', max_length=20)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cvss_vector', models.CharField(blank=True, max_length=255)),
                ('av', models.CharField(blank=True, choices=[('N', 'Network'), ('A', 'Adjacent'), ('L', 'Local'), ('P', 'Physical')], max_length=20)),
                ('ac', models.CharField(blank=True, choices=[('L', 'Low'), ('H', 'High')], max_length=20)),
                ('pr', models.CharField(blank=True, choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], max_length=20)),
                ('ui', models.CharField(blank=True, choices=[('N', 'None'), ('R', 'Required')], max_length=20)),
                ('s', models.CharField(blank=True, choices=[('U', 'Unchanged'), ('C', 'Changed')], max_length=20)),
                ('c', models.CharField(blank=True, choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], max_length=20)),
                ('i', models.CharField(blank=True, choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], max_length=20)),
                ('a', models.CharField(blank=True, choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], max_length=20)),
                ('description', models.TextField(help_text='Executive summary of the finding')),
                ('details', models.TextField(blank=True, help_text='Technical details of how the vulnerability was discovered')),
                ('impact', models.TextField(help_text='Business/technical impact if exploited')),
                ('likelihood', models.TextField(help_text='Likelihood of exploitation')),
                ('recommendations', models.TextField(help_text='Remediation recommendations')),
                ('supporting_evidence', models.TextField(blank=True, help_text='Additional evidence, logs, screenshots description')),
                ('references', models.TextField(blank=True, help_text='External references (CVE, CWE, OWASP, etc.)')),
                ('cwe_id', models.CharField(blank=True, help_text='CWE ID (e.g., CWE-79)', max_length=50)),
                ('cve_id', models.CharField(blank=True, help_text='CVE ID if applicable', max_length=50)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('remediated_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_findings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_findings', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='engagements.engagement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FindingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal only comment (not visible to client)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='findings.finding')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FindingCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'Text Area'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('SELECT', 'Select Dropdown'), ('CHECKBOX', 'Checkbox'), ('URL', 'URL')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for SELECT type')),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_custom_fields', to='organizations.organization')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FindingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='finding_images/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='findings.finding')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['engagement', 'severity'], name='findings_fi_engagem_2f4427_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['engagement', 'status'], name='findings_fi_engagem_e629e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='findingcustomfield',
            unique_together={('organization', 'name')},
        ),
    ]
