# Generated by Django 5.0.6 on 2026-04-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0004_finding_pentest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='is_key_finding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='finding',
            name='impact_rating',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='finding',
            name='likelihood_rating',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10),
        ),
    ]
