# Generated by Django 5.0.6 on 2026-05-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0005_finding_is_key_finding'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='level_of_access',
            field=models.CharField(blank=True, choices=[('UNAUTHENTICATED', 'Unauthenticated'), ('AUTHENTICATED', 'Authenticated')], max_length=20),
        ),
    ]
