# Generated by Django 5.0.6 on 2026-04-15 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('engagement_type', models.CharField(choices=[('WEB_APP', 'Web Application Penetration Test'), ('MOBILE_APP', 'Mobile Application Penetration Test'), ('NETWORK', 'Network Infrastructure Penetration Test'), ('API', 'API Penetration Test'), ('CLOUD', 'Cloud Infrastructure Penetration Test'), ('SOCIAL', 'Social Engineering Assessment'), ('PHYSICAL', 'Physical Security Assessment'), ('RED_TEAM', 'Red Team Exercise'), ('WIRELESS', 'Wireless Security Assessment'), ('THICK_CLIENT', 'Thick Client Application Test'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('REPORTING', 'Reporting'), ('REVIEW', 'Under Review'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('report_due_date', models.DateField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, help_text='Description of in-scope targets')),
                ('out_of_scope', models.TextField(blank=True, help_text='Description of out-of-scope items')),
                ('objectives', models.TextField(blank=True, help_text='Engagement objectives')),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('allow_client_access', models.BooleanField(default=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead_pentester', models.ForeignKey(help_text='Primary penetration tester', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_engagements', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='organizations.organization')),
                ('project_manager', models.ForeignKey(help_text='Project manager overseeing engagement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_engagements', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(blank=True, help_text='Additional team members', related_name='engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Engagements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='engagement_attachments/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='engagements.engagement')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='engagements.engagement')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
