# Generated by Django 5.0.6 on 2026-04-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='skip_weekends',
            field=models.BooleanField(default=False, help_text='Exclude weekends when calculating engagement duration'),
        ),
    ]
