# Generated by Django 5.0.6 on 2026-05-14 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0002_add_skip_weekends'),
        ('organizations', '0002_alter_organization_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrcFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GrcFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('NIST_CSF_2', 'NIST Cybersecurity Framework 2.0'), ('NIST_800_171_R3', 'NIST SP 800-171 Rev 3'), ('ISO_27001_2022', 'ISO/IEC 27001:2022'), ('SOC2', 'SOC 2 Type II'), ('HIPAA', 'HIPAA Security Rule')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GrcControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('statement', models.TextField(blank=True)),
                ('discussion', models.TextField(blank=True)),
                ('is_category', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='grc.grccontrol')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='grc.grcfamily')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('family', 'control_id')},
            },
        ),
        migrations.CreateModel(
            name='GrcControlStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('IMPLEMENTED', 'Implemented'), ('PARTIALLY_IMPLEMENTED', 'Partially Implemented'), ('NOT_APPLICABLE', 'Not Applicable'), ('PLANNED', 'Planned')], default='NOT_STARTED', max_length=30)),
                ('implementation_notes', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='grc.grccontrol')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_grc_controls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['control__order'],
            },
        ),
        migrations.CreateModel(
            name='GrcEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='grc_evidence/')),
                ('url', models.URLField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('control_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='grc.grccontrolstatus')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='grcfamily',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='grc.grcframework'),
        ),
        migrations.CreateModel(
            name='GrcProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grc_assessor', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grc_created', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grc_projects', to='engagements.engagement')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='grc.grcframework')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grc_projects', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='grccontrolstatus',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_statuses', to='grc.grcproject'),
        ),
        migrations.AlterUniqueTogether(
            name='grcfamily',
            unique_together={('framework', 'identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='grccontrolstatus',
            unique_together={('project', 'control')},
        ),
    ]
